trigger:
  - main

pool:
  vmImage: "windows-latest"

variables:
  - name: serviceConnection
    value: "WRKSHP_IS_ME-MngEnvMCAP675646-emknafo-1 (64c3d212-40ed-4c6d-a825-6adfbdf25dad)-4734"
  - name: workingDirectory
    value: $(System.DefaultWorkingDirectory)/src/helloworldexample

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - task: UseDotNet@2
            inputs:
              packageType: "sdk"
              version: "8.x"
              installationPath: $(Agent.ToolsDirectory)/dotnet
          - script: dotnet build --configuration Release
            displayName: "dotnet build $(Build.SourcesDirectory)/src/helloworldexample/WRKSHP_FunctionApps.csproj"
            workingDirectory: $(workingDirectory)
          - task: PublishBuildArtifacts@1
            inputs:
              pathtoPublish: "$(workingDirectory)"
              artifactName: "drop"
              publishLocation: "Container"
  - stage: Deploy
    dependsOn: Build
    jobs:
      - deployment: Deploy
        environment: "WRKSHP_IS_fnapp_dev"
        strategy:
          runOnce:
            deploy:
              steps:
                - task: UseDotNet@2
                  inputs:
                    packageType: "sdk"
                    version: "8.x"
                    installationPath: $(Agent.ToolsDirectory)/dotnet
                - script: dotnet publish --configuration Release --output $(Build.ArtifactStagingDirectory)/publish
                  displayName: "dotnet publish $(Build.SourcesDirectory)/src/helloworldexample/WRKSHP_FunctionApps.csproj"
                - task: AzureFunctionApp@1
                  inputs:
                    azureSubscription: "$(serviceConnection)"
                    appType: "functionApp"
                    appName: "helloworldexample"
                    package: $(Build.ArtifactStagingDirectory)/publish
                    deploymentMethod: "auto"
